spring:
  main:
    banner-mode: off

    #  datasource:
    #    url: jdbc:postgresql://localhost:5432/testDb
    #    username: root
    #    password: root

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

#  liquibase:
#    change-log: classpath:/db/changelog/changelog-master.xml

#app:
#  server:
#    url: ${app.server.url}
