spring:
  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

#  security:
#    oauth2:
#      resource-server:
#        opaquetoken:
#          client-id: 41846f33387e9d650259
#          client-secret: 1351468d08b0e6079f17642e493a666b32f873a2


  #  datasource:
#    url: jdbc:h2:file:./db
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: ${jwt.header}
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}


#  h2:
#    console:
#      enabled: true
#      path: /h2-console/


